import { exerciseType } from "../types/Exercise";

export const TestExercises: exerciseType[] = [
  {
    id: 1,
    name: "Bench Press",
    muscletype: "Chest",
    othermusclesworked: ["Triceps", "Shoulders"],
  },
  {
    id: 2,
    name: "Incline Bench Press",
    muscletype: "Chest",
    othermusclesworked: ["Triceps", "Shoulders"],
  },
  {
    id: 3,
    name: "Dumbbell Flyes",
    muscletype: "Chest",
    othermusclesworked: ["Chest"],
  },
  {
    id: 4,
    name: "Push-Ups",
    muscletype: "Chest",
    othermusclesworked: ["Triceps", "Shoulders"],
  },
  {
    id: 5,
    name: "Chest Press Machine",
    muscletype: "Chest",
    othermusclesworked: ["Triceps", "Shoulders"],
  },
  {
    id: 6,
    name: "Cable Crossovers",
    muscletype: "Chest",
    othermusclesworked: ["Chest"],
  },
  {
    id: 7,
    name: "Lat Pulldown",
    muscletype: "Back",
    othermusclesworked: ["Biceps"],
  },
  {
    id: 8,
    name: "Barbell Row",
    muscletype: "Back",
    othermusclesworked: ["Biceps"],
  },
  {
    id: 9,
    name: "Pull-Ups",
    muscletype: "Back",
    othermusclesworked: ["Biceps"],
  },
  {
    id: 10,
    name: "Seated Cable Rows",
    muscletype: "Back",
    othermusclesworked: ["Biceps"],
  },
  {
    id: 11,
    name: "Dead Hangs",
    muscletype: "Back",
    othermusclesworked: ["Forearms"],
  },
  {
    id: 12,
    name: "T-Bar Rows",
    muscletype: "Back",
    othermusclesworked: ["Biceps"],
  },
  {
    id: 13,
    name: "Squat",
    muscletype: "Quads",
    othermusclesworked: ["Glutes", "Hamstrings"],
  },
  {
    id: 14,
    name: "DeadLift",
    muscletype: "Lower Back",
    othermusclesworked: ["Hamstrings", "Forearms"],
  },
  {
    id: 15,
    name: "Romanian DeadLift",
    muscletype: "Hamstrings",
    othermusclesworked: ["Lower Back"],
  },
  {
    id: 16,
    name: "Leg Press",
    muscletype: "Quads",
    othermusclesworked: ["Glutes", "Calves"],
  },
  {
    id: 17,
    name: "Walking Lunges",
    muscletype: "Quads",
    othermusclesworked: ["Glutes"],
  },
  {
    id: 18,
    name: "Leg Extensions",
    muscletype: "Quads",
    othermusclesworked: ["Quads"],
  },
  {
    id: 19,
    name: "Calf Raises",
    muscletype: "Calves",
    othermusclesworked: ["Soleus"],
  },
  {
    id: 20,
    name: "Overhead Press",
    muscletype: "Shoulders",
    othermusclesworked: ["Triceps"],
  },
  {
    id: 21,
    name: "Lateral Raises",
    muscletype: "Shoulders",
    othermusclesworked: ["Side Delts"],
  },
  {
    id: 22,
    name: "Front Raises",
    muscletype: "Front Delts",
    othermusclesworked: ["Side Delts"],
  },
  {
    id: 23,
    name: "Upright Rows",
    muscletype: "Traps",
    othermusclesworked: ["Side Delts"],
  },
  {
    id: 24,
    name: "Arnold Press",
    muscletype: "Shoulders",
    othermusclesworked: ["Triceps"],
  },
  {
    id: 25,
    name: "Shrugs",
    muscletype: "Traps",
    othermusclesworked: ["Upper Back"],
  },
  {
    id: 26,
    name: "Face Pulls",
    muscletype: "Rear Delts",
    othermusclesworked: ["Traps"],
  },
  {
    id: 27,
    name: "Lateral Raises (Machine)",
    muscletype: "Side Delts",
    othermusclesworked: ["Front Delts"],
  },
  {
    id: 28,
    name: "Bicep Curls",
    muscletype: "Biceps",
    othermusclesworked: ["Forearms"],
  },
  {
    id: 29,
    name: "Tricep Dips",
    muscletype: "Triceps",
    othermusclesworked: ["Chest", "Shoulders"],
  },
  {
    id: 30,
    name: "Tricep Kickbacks",
    muscletype: "Triceps",
    othermusclesworked: [],
  },
  {
    id: 31,
    name: "Close-Grip Bench Press",
    muscletype: "Triceps",
    othermusclesworked: ["Chest", "Shoulders"],
  },
  {
    id: 32,
    name: "Hammer Curls",
    muscletype: "Biceps",
    othermusclesworked: ["Forearms"],
  },
  {
    id: 33,
    name: "Skull Crushers",
    muscletype: "Triceps",
    othermusclesworked: ["Forearms"],
  },
  {
    id: 34,
    name: "Preacher Curls",
    muscletype: "Biceps",
    othermusclesworked: ["Forearms"],
  },
  {
    id: 35,
    name: "Tricep Rope Pushdowns",
    muscletype: "Triceps",
    othermusclesworked: [],
  },
];
