name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  lint:
    name: Code Standards
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 18

      - name: "Install npm@latest"
        run: npm i -g npm@latest

      - name: "Install dependencies"
        uses: bahmutov/npm-install@v1.6.0

      - name: "lint code"
        run: npm run lint --if-present
      
